name: Build ACA table

on:
  schedule:
    - cron: '13 9 * * *'   # daily at 09:13 UTC (change if you want)
  workflow_dispatch:        # allow manual runs from the Actions tab
  push:
    paths:
      - 'map/generate_table.py'
      - '.github/workflows/build-table.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to push the updated HTML
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 lxml

      - name: Generate table
        run: |
          python map/generate_table.py

      - name: Commit and push changes
        run: |
          if git status --porcelain | grep -E '^ M|^\?\?' | grep 'docs/aca_table.html'; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/aca_table.html
            git commit -m "Update ACA region table (CI)"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Publish public URL to job summary
        run: |
          OWNER=${GITHUB_REPOSITORY%/*}
          REPO=${GITHUB_REPOSITORY#*/}
          echo "The table will be available at:" >> $GITHUB_STEP_SUMMARY
          echo "**https://${OWNER}.github.io/${REPO}/aca_table.html**" >> $GITHUB_STEP_SUMMARY
